/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package evil_fortune_teller;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
